
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class StatRevenueFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatRevenueFrm.class.getName());

    /**
     * Creates new form StatRevenueFrm
     */
    public StatRevenueFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        btnStat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ngày bắt đầu");

        jLabel2.setText("Ngày kết thúc");

        txtStartDate.addActionListener(this::txtStartDateActionPerformed);

        btnStat.setText("Thống kê");
        btnStat.addActionListener(this::btnStatActionPerformed);

        tblStatResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Số lượng bán", "Tổng doanh thu"
            }
        ));
        tblStatResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStatResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStatResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStat)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnStat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void btnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatActionPerformed
try {
        String startDate = txtStartDate.getText().trim();
        String endDate = txtEndDate.getText().trim();

        // 1. Kiểm tra rỗng
        if (startDate.isEmpty() || endDate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ ngày!");
            return;
        }

        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // Đảm bảo ngày nhập vào là có thật
        try {
            java.util.Date dStart = sdf.parse(startDate);
            java.util.Date dEnd = sdf.parse(endDate);
            if (dStart.after(dEnd)) {
                
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Ngày bắt đầu không được lớn hơn ngày kết thúc", 
                    "Lỗi nhập liệu", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return; 
            }
        } catch (java.text.ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ (dd/MM/yyyy)!");
            return;
        }

        
        StatRevenueCtr ctr = new StatRevenueCtr();
        List<Dish> resultList = ctr.getDishStat(startDate, endDate);

        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblStatResult.getModel();
        model.setRowCount(0); 

        if (resultList.isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "Không có dữ liệu thống kê trong thời gian này");
        } else {
            
            for (Dish d : resultList) {
                model.addRow(new Object[]{
                    d.getId(), 
                    d.getName(), 
                    d.getTotalSold(), 
                    String.format("%,.0f", d.getTotalRevenue())
                });
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Đã thống kê từ Database!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnStatActionPerformed

    private void tblStatResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStatResultMouseClicked
        int row = tblStatResult.getSelectedRow();
    if (row != -1) {
        
        int dishId = Integer.parseInt(tblStatResult.getValueAt(row, 0).toString());
        
        
        String startDate = txtStartDate.getText().trim();
        String endDate = txtEndDate.getText().trim();

        
        StatRevenueCtr ctr = new StatRevenueCtr();
        List<Bill> listBills = ctr.getBillDetails(dishId, startDate, endDate);

        
        RevenueDetailFrm detailFrm = new RevenueDetailFrm();
        javax.swing.table.DefaultTableModel modelDetail = 
            (javax.swing.table.DefaultTableModel) detailFrm.tblBillDetail.getModel();
        
        modelDetail.setRowCount(0); 

        
        if (listBills.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Món này không có hóa đơn trong thời gian chọn!");
        } else {
            for (Bill b : listBills) {
                modelDetail.addRow(new Object[]{
                    b.getId(),
                    b.getNote(), 
                    b.getPaymentDate(),
                    b.getQuantity(), 
                    String.format("%,.0f", b.getTotalAmount())
                });
            }
            detailFrm.setVisible(true); 
        }
    }
    }//GEN-LAST:event_tblStatResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StatRevenueFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStatResult;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}